---
version: 2

env:
  - distro: centos7
jobs:
  build:
    docker:
      - image: 
    steps:
      - checkout
      - run: wget -O ${PWD}/tests/test.sh https://gist.githubusercontent.com/geerlingguy/73ef1e5ee45d8694570f334be385e181/raw/
      - run: chmod +x ${PWD}/tests/test.sh
      - run: ${PWD}/tests/test.sh
